### ISSUE TITLE
Pre-release Checklist

### ISSUE THREAD

**Issue by zhevron** [zhevron/go-csselect#1]
- [ ] Tag parsing (tag)
- [ ] Attribute selector parsing ([attr='value'])
- [ ] Class selector parsing (tag.class)
- [ ] ID selector parsing (tag#id)
- [ ] Descendant selector parsing (tag child)
- [ ] Child selector parsing (tag > child)
- [ ] Adjacent selector parsing (tag + child)
- [ ] General sibling selector parsing (tag ~ child)
